/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    2025.2.0.48.0
    Soft IP Version: 2.7.0
    2026 04 30 21:23:37
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module mipi_cross_clk_fifo (wr_clk_i, rd_clk_i, rst_i, rp_rst_i, wr_en_i,
    rd_en_i, wr_data_i, full_o, empty_o, rd_data_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  wr_clk_i;
    input  rd_clk_i;
    input  rst_i;
    input  rp_rst_i;
    input  wr_en_i;
    input  rd_en_i;
    input  [33:0]  wr_data_i;
    output  full_o;
    output  empty_o;
    output  [33:0]  rd_data_o;
endmodule