#-- Lattice Semiconductor Corporation Ltd.
#-- Map run script generated by Radiant

set ret 0
if {[catch {

if {![file exists {C:/Users/Bernhard/my_designs/mira_test/impl_1}]} {
  file mkdir {C:/Users/Bernhard/my_designs/mira_test/impl_1}
}
cd {C:/Users/Bernhard/my_designs/mira_test/impl_1}

sys_set_attribute -gui on -msg {C:/Users/Bernhard/my_designs/mira_test/promote.xml}
msg_load {C:/Users/Bernhard/my_designs/mira_test/promote.xml}
des_set_project_udb -in {mira_test_impl_1_syn.udb} -out {mira_test_impl_1_map.udb} -milestone map -pm je5d00
des_set_reference_udb -clean
map_set_option {pdc_file "C:/Users/Bernhard/my_designs/mira_test/source/impl_1/impl_1.pdc"}
# map option
map_set_option { report_symbol_cross_reference false report_signal_cross_reference false infer_gsr false  ignore_constraint_errors false vio false}
map_run

} out]} {
   puts $out
   set ret 1
}
exit -force ${ret}
