/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    2025.2.0.48.0
    Soft IP Version: 1.9.0
    2026 04 30 13:50:29
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module mipi_dphy_rx (sync_clk_i, sync_rst_i, lmmi_clk_i, lmmi_resetn_i,
    lmmi_wdata_i, lmmi_wr_rdn_i, lmmi_offset_i, lmmi_request_i, lmmi_ready_o,
    lmmi_rdata_o, lmmi_rdata_valid_o, hs_rx_data_o, hs_rx_data_sync_o,
    clk_p_io, clk_n_io, data_p_io, data_n_io, pd_dphy_i, clk_byte_o, ready_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  sync_clk_i;
    input  sync_rst_i;
    input  lmmi_clk_i;
    input  lmmi_resetn_i;
    input  [3:0]  lmmi_wdata_i;
    input  lmmi_wr_rdn_i;
    input  [4:0]  lmmi_offset_i;
    input  lmmi_request_i;
    output  lmmi_ready_o;
    output  [3:0]  lmmi_rdata_o;
    output  lmmi_rdata_valid_o;
    output  [31:0]  hs_rx_data_o;
    output  [1:0]  hs_rx_data_sync_o;
    inout  clk_p_io;
    inout  clk_n_io;
    inout  [1:0]  data_p_io;
    inout  [1:0]  data_n_io;
    input  pd_dphy_i;
    output  clk_byte_o;
    output  ready_o;
endmodule