/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    2025.2.0.48.0
    Soft IP Version: 2.5.0
    2026 07 06 10:19:58
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module process_image_out_fifo (clk_i, rst_i, wr_en_i, rd_en_i, wr_data_i,
    full_o, empty_o, almost_full_o, almost_empty_o, rd_data_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  clk_i;
    input  rst_i;
    input  wr_en_i;
    input  rd_en_i;
    input  [63:0]  wr_data_i;
    output  full_o;
    output  empty_o;
    output  almost_full_o;
    output  almost_empty_o;
    output  [63:0]  rd_data_o;
endmodule