#
# demo scrolling graph server generated by Gemini AI
# ensure 'smoothie.js' is available in server directory
# run the server, then connect to http://<host>:8002
#

import asyncio
import random
import time
import os
from fastapi import FastAPI, WebSocket
from fastapi.responses import HTMLResponse, FileResponse, Response

app = FastAPI()

HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <title>Real-Time Rolling Graph</title>
    <!-- Pointed to your local Python server file, no internet needed -->
    <script src="/smoothie.js"></script>
    <style>
        body { background: #111; color: #fff; font-family: sans-serif; text-align: center; }
        canvas { background: #222; margin-top: 50px; border: 1px solid #444; }
    </style>
</head>
<body>
    <h2>Live Data Stream (25 pts/sec)</h2>
    <canvas id="chart" width="800" height="400"></canvas>

    <script>
        window.onload = function() {
            const chartElement = document.getElementById("chart");
            
            // Configuration options
            const smoothie = new SmoothieChart({
                grid: { strokeStyle: '#333', fillStyle: '#111', lineWidth: 1, millisPerLine: 250, verticalSections: 6 },
                labels: { fillStyle: '#fff' },
                tooltip: true,
                millisPerPixel: 4
            });
            
            smoothie.streamTo(chartElement, 40); 

            const line = new TimeSeries();
            smoothie.addTimeSeries(line, { strokeStyle: '#00ff00', fillStyle: 'rgba(0, 255, 0, 0.1)', lineWidth: 2 });

            const ws = new WebSocket("ws://localhost:8002/ws");
            
            ws.onopen = function() {
                console.log("WebSocket connection established successfully");
            };

            ws.onmessage = function(event) {
                const data = JSON.parse(event.data);
                line.append(data.time, data.value);
            };

            ws.onerror = function(error) {
                console.error("WebSocket Error: ", error);
            };
        };
    </script>
</body>
</html>
"""

@app.get("/")
async def get():
    return HTMLResponse(HTML_TEMPLATE)

# Route to serve the downloaded library locally
@app.get("/smoothie.js")
async def get_smoothie():
    if os.path.exists("smoothie.js"):
        return FileResponse("smoothie.js", media_type="application/javascript")
    return Response(content="console.error('smoothie.js file missing locally!');", media_type="application/javascript", status_code=404)

# Silence Chrome DevTools metadata lookup noise
@app.get("/.well-known/appspecific/com.chrome.devtools.json", include_in_schema=False)
async def devtools_noise():
    return Response(status_code=204)

# Silence standard favicon noise
@app.get("/favicon.ico", include_in_schema=False)
async def favicon():
    return Response(status_code=204)

@app.websocket("/ws")
async def websocket_endpoint(websocket: WebSocket):
    await websocket.accept()
    interval = 1.0 / 25.0 
    
    try:
        while True:
            start_time = time.time()
            current_timestamp_ms = int(time.time() * 1000)
            mock_value = random.uniform(10, 90) 
            
            await websocket.send_json({
                "time": current_timestamp_ms,
                "value": mock_value
            })
            
            elapsed = time.time() - start_time
            sleep_time = max(0, interval - elapsed)
            await asyncio.sleep(sleep_time)
            
    except Exception as e:
        print(f"Connection closed: {e}")
    finally:
        try:
            await websocket.close()
        except:
            pass

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="127.0.0.1", port=8002)
